### ISSUE TITLE
Remote datawraps

### ISSUE THREAD

**Issue by courcelm** [tariqdaouda/pyGeno#13]
The following example doesn`t work.

> > > B.printRemoteDatawraps()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/src/app/pyGeno/bootstrap.py", line 45, in printRemoteDatawraps
> > >     l = listRemoteDatawraps(location)
> > >   File "/usr/src/app/pyGeno/bootstrap.py", line 15, in listRemoteDatawraps
> > >     js = json.loads(response.read())
> > >   File "/usr/local/lib/python2.7/json/**init**.py", line 339, in loads
> > >     return _default_decoder.decode(s)
> > >   File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
> > >     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> > >   File "/usr/local/lib/python2.7/json/decoder.py", line 380, in raw_decode
> > >     obj, end = self.scan_once(s, idx)
> > > ValueError: Expecting property name: line 6 column 3 (char 113)

**Comment by tariqdaouda** [comment]
Remote datawraps where supposed to be a repository of mainly reference genomes for different species. However most of users are only interested in a few versions of Human and Mouse genomes.

I have stopped maintaining them because it's a lot of work for something that hardly nobody seems to be using. But the code is still there just in case someone would like to re-implement them because I still think it would be great to have a repository of many genomes for a lot of species.
